# Generated by Django 6.1.1 on 2026-09-13 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=7)),
                ('userpsw', models.CharField(max_length=6)),
                ('avatar', models.CharField(default='', max_length=64)),
                ('role', models.CharField(blank=True, max_length=16, null=True)),
                ('display_role', models.CharField(blank=True, max_length=16, null=True)),
                ('final_role', models.CharField(blank=True, max_length=16, null=True)),
                ('choice', models.JSONField(default=dict)),
                ('submitted', models.BooleanField(default=False)),
                ('vote_target', models.CharField(default='', max_length=7)),
                ('voted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(default='waiting', max_length=10)),
                ('phase', models.CharField(choices=[('waiting', 'waiting'), ('op', 'op'), ('reveal', 'reveal'), ('result', 'result')], default='waiting', max_length=10)),
                ('board', models.JSONField(default=dict)),
                ('center', models.JSONField(default=list)),
                ('resolved_flag', models.BooleanField(default=False)),
                ('op_start_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='room.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='room.room'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'userid')},
        ),
    ]
