# Generated by Django 6.1.1 on 2026-09-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='fake_role',
        ),
    ]
