# Generated by Django 6.1.1 on 2026-09-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ops',
            field=models.JSONField(default=list),
        ),
    ]
